// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protobuf/service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *LongString) Reset() {
	*x = LongString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongString) ProtoMessage() {}

func (x *LongString) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongString.ProtoReflect.Descriptor instead.
func (*LongString) Descriptor() ([]byte, []int) {
	return file_protobuf_service_proto_rawDescGZIP(), []int{0}
}

func (x *LongString) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price    float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Datetime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Data     string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_protobuf_service_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Object) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *Object) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LargeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Object `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *LargeResponse) Reset() {
	*x = LargeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeResponse) ProtoMessage() {}

func (x *LargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeResponse.ProtoReflect.Descriptor instead.
func (*LargeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_service_proto_rawDescGZIP(), []int{2}
}

func (x *LargeResponse) GetData() []*Object {
	if x != nil {
		return x.Data
	}
	return nil
}

type SimpleObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price    float32         `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Foo      int64           `protobuf:"varint,3,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar      float64         `protobuf:"fixed64,4,opt,name=bar,proto3" json:"bar,omitempty"`
	Lol      string          `protobuf:"bytes,5,opt,name=lol,proto3" json:"lol,omitempty"`
	Kek      *NestedObject   `protobuf:"bytes,6,opt,name=kek,proto3" json:"kek,omitempty"`
	Cheburek []*NestedObject `protobuf:"bytes,7,rep,name=cheburek,proto3" json:"cheburek,omitempty"`
}

func (x *SimpleObject) Reset() {
	*x = SimpleObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleObject) ProtoMessage() {}

func (x *SimpleObject) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleObject.ProtoReflect.Descriptor instead.
func (*SimpleObject) Descriptor() ([]byte, []int) {
	return file_protobuf_service_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleObject) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleObject) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SimpleObject) GetFoo() int64 {
	if x != nil {
		return x.Foo
	}
	return 0
}

func (x *SimpleObject) GetBar() float64 {
	if x != nil {
		return x.Bar
	}
	return 0
}

func (x *SimpleObject) GetLol() string {
	if x != nil {
		return x.Lol
	}
	return ""
}

func (x *SimpleObject) GetKek() *NestedObject {
	if x != nil {
		return x.Kek
	}
	return nil
}

func (x *SimpleObject) GetCheburek() []*NestedObject {
	if x != nil {
		return x.Cheburek
	}
	return nil
}

type NestedObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I     int32  `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	Am    int64  `protobuf:"zigzag64,2,opt,name=am,proto3" json:"am,omitempty"`
	Groot string `protobuf:"bytes,3,opt,name=groot,proto3" json:"groot,omitempty"`
}

func (x *NestedObject) Reset() {
	*x = NestedObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedObject) ProtoMessage() {}

func (x *NestedObject) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedObject.ProtoReflect.Descriptor instead.
func (*NestedObject) Descriptor() ([]byte, []int) {
	return file_protobuf_service_proto_rawDescGZIP(), []int{4}
}

func (x *NestedObject) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *NestedObject) GetAm() int64 {
	if x != nil {
		return x.Am
	}
	return 0
}

func (x *NestedObject) GetGroot() string {
	if x != nil {
		return x.Groot
	}
	return ""
}

var File_protobuf_service_proto protoreflect.FileDescriptor

var file_protobuf_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x4c, 0x6f, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7a, 0x0a, 0x06, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x0d, 0x4c, 0x61, 0x72, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc8,
	0x01, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6c, 0x12, 0x28, 0x0a, 0x03, 0x6b,
	0x65, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x03, 0x6b, 0x65, 0x6b, 0x12, 0x32, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x62, 0x75, 0x72, 0x65,
	0x6b, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x08, 0x63, 0x68, 0x65, 0x62, 0x75, 0x72, 0x65, 0x6b, 0x22, 0x42, 0x0a, 0x0c, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x02, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x6f, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x6f, 0x74, 0x42, 0x0d, 0x5a,
	0x0b, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_service_proto_rawDescOnce sync.Once
	file_protobuf_service_proto_rawDescData = file_protobuf_service_proto_rawDesc
)

func file_protobuf_service_proto_rawDescGZIP() []byte {
	file_protobuf_service_proto_rawDescOnce.Do(func() {
		file_protobuf_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_service_proto_rawDescData)
	})
	return file_protobuf_service_proto_rawDescData
}

var file_protobuf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_service_proto_goTypes = []interface{}{
	(*LongString)(nil),            // 0: protobuf.LongString
	(*Object)(nil),                // 1: protobuf.Object
	(*LargeResponse)(nil),         // 2: protobuf.LargeResponse
	(*SimpleObject)(nil),          // 3: protobuf.SimpleObject
	(*NestedObject)(nil),          // 4: protobuf.NestedObject
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_protobuf_service_proto_depIdxs = []int32{
	5, // 0: protobuf.Object.datetime:type_name -> google.protobuf.Timestamp
	1, // 1: protobuf.LargeResponse.data:type_name -> protobuf.Object
	4, // 2: protobuf.SimpleObject.kek:type_name -> protobuf.NestedObject
	4, // 3: protobuf.SimpleObject.cheburek:type_name -> protobuf.NestedObject
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_service_proto_init() }
func file_protobuf_service_proto_init() {
	if File_protobuf_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_service_proto_goTypes,
		DependencyIndexes: file_protobuf_service_proto_depIdxs,
		MessageInfos:      file_protobuf_service_proto_msgTypes,
	}.Build()
	File_protobuf_service_proto = out.File
	file_protobuf_service_proto_rawDesc = nil
	file_protobuf_service_proto_goTypes = nil
	file_protobuf_service_proto_depIdxs = nil
}
